export const dynamic = 'force-dynamic';
import Link from 'next/link';
import HeroGearOptimizer from '../HeroGearOptimizer';

export const metadata = { title: 'Hero Gear Optimizer (Preview) · K710' };

export default async function HeroGearOptimizerPage({ searchParams: searchParamsPromise }) {
  const searchParams = await searchParamsPromise;
  const memberId = typeof searchParams?.member_id === 'string' ? searchParams.member_id : '';
  return <main className="armory hero-gear-page"><div className="armory-atmos" aria-hidden="true"/><span className="armory-rack-l" aria-hidden="true"/><span className="armory-rack-r" aria-hidden="true"/><div className="armory-inner hero-gear-inner"><div className="hero-gear-nav"><Link href={`/tools?category=Hero Gear${memberId ? `&member_id=${encodeURIComponent(memberId)}` : ''}`}>← Hero Gear tools</Link><span className="k-mark">Hero Gear · Preview</span></div><header className="armory-head hero-gear-head"><h1 className="k-display armory-title">Hero Gear Optimizer</h1><p className="k-narrative armory-lede">Set current and target state for all 12 Hero Gear pieces across Level, Imbuement, and Mythic quality. Game costs are not yet sourced — see the Preview notice below.</p></header><HeroGearOptimizer/></div><footer className="hero-gear-source">No freely-reusable source was found for this game&apos;s Hero Gear cost model (XP, Forgehammers, Mithril, Mythic Gear). This tool ships with the full workflow and placeholder cost data so real numbers can be added later without changing how it works — see the Preview notice in the tool above.</footer><style>{`.hero-gear-page{color:var(--parchment)}.hero-gear-inner{width:min(1380px,100%);padding-top:clamp(76px,9vh,108px)}.hero-gear-nav{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:24px;padding-bottom:15px;border-bottom:1px solid var(--edge)}.hero-gear-nav a{color:var(--brass);font-family:var(--font-body);font-size:12px;letter-spacing:.05em;text-decoration:none}.hero-gear-nav a:hover{color:var(--gold-hot)}.hero-gear-head{margin-bottom:24px}.hero-gear-head .armory-lede{max-width:760px}.hero-gear-source{width:min(1380px,100%);margin:20px auto 0;padding:14px 4px;color:var(--t-secondary);font-size:11px;line-height:1.6}@media(max-width:620px){.hero-gear-nav{align-items:flex-start;flex-direction:column}.hero-gear-inner{padding-top:70px}}`}</style></main>;
}
