'use client';
import {useEffect,useMemo,useState} from 'react';
import {calculateCosts,calculateReach,duration,exportPlanCsv,levelLabel,numberValue,RESOURCE_LABELS} from '../../lib/costPlanner.mjs';
import styles from './CostPlanner.module.css';
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
function LevelSelect({item,value,onChange,label,minimum='0'}){
 const min=item.levels.findIndex(l=>l.level===minimum);
 return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="0" disabled={minimum!=='0'}>Not started</option>{item.levels.map((l,i)=><option key={l.level} value={l.level} disabled={i<min}>{levelLabel(l.level)}</option>)}</select>;
}
export default function CostPlanner({dataset,toolKey,construction=false}){
 const first=dataset.items[0];
 const [selections,setSelections]=useState([{id:first.id,current:construction?'1':'0',target:construction?'2':first.levels[0].level}]);
 const [currentLevels,setCurrentLevels]=useState({}),[inventory,setInventory]=useState({}),[modifiers,setModifiers]=useState({}),[includePrerequisites,setIncludePrerequisites]=useState(true),[mode,setMode]=useState('cost'),[result,setResult]=useState(null),[error,setError]=useState(''),[saveStatus,setSaveStatus]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[candidate,setCandidate]=useState(first.id),[baselineSearch,setBaselineSearch]=useState('');
 const resources=construction?['bread','wood','stone','iron','truegold','temperedTruegold']:toolKey==='academy'?['bread','wood','stone','iron','gold']:toolKey==='war-academy'?['truegold_dust','gold','bread','wood','stone','iron']:['truegold_dust','temperedTruegold','gold','bread','wood','stone','iron'];
 const categories=[...new Set(dataset.items.map(i=>i.category))];
 const filtered=useMemo(()=>dataset.items.filter(i=>(!category||i.category===category)&&`${i.name} ${i.levels[0]?.effect?.type||''}`.toLowerCase().includes(search.toLowerCase())),[dataset,search,category]);
 const chosen=filtered.find(i=>i.id===candidate)||filtered[0];
 const stateKey=`costs-${toolKey}`;
 useEffect(()=>{
  const controller=new AbortController();
  fetch(`/api/tool-state/${stateKey}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Saved inputs could not be loaded.');return r.json();}).then(({state})=>{
   if(!state)return;
   const safe=(state.selections||[]).filter(s=>{const i=dataset.items.find(x=>x.id===s.id);return i&&(s.current==='0'||i.levels.some(l=>l.level===s.current))&&i.levels.some(l=>l.level===s.target);});
   if(safe.length)setSelections(safe);
   setCurrentLevels(state.currentLevels||{});setInventory(state.inventory||{});setModifiers(state.modifiers||{});setIncludePrerequisites(state.includePrerequisites!==false);setSaveStatus('Saved plan loaded.');
  }).catch(e=>{if(e.name!=='AbortError')setSaveStatus(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[stateKey,dataset]);
 function changed(){setResult(null);setError('');setSaveStatus('Unsaved changes');}
 function updateSelection(id,key,value){changed();if(key==='current')setCurrentLevels(c=>({...c,[id]:value}));setSelections(prev=>prev.map(s=>{if(s.id!==id)return s;const item=dataset.items.find(i=>i.id===id),next={...s,[key]:value};if(key==='current'){if(item.levels.findIndex(l=>l.level===next.target)<item.levels.findIndex(l=>l.level===value))next.target=value;}return next;}));}
 function add(){if(!chosen)return;changed();const current=currentLevels[chosen.id]||'0',i=chosen.levels.findIndex(l=>l.level===current),next=chosen.levels[Math.min(i+1,chosen.levels.length-1)].level;setSelections(prev=>prev.some(s=>s.id===chosen.id)?prev:[...prev,{id:chosen.id,current,target:next}]);}
 function modifier(key,value){changed();setModifiers(m=>({...m,[key]:value}));}
 async function save(){setSaving(true);try{const r=await fetch(`/api/tool-state/${stateKey}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:{selections,currentLevels,inventory,modifiers,includePrerequisites}})});if(!r.ok)throw Error('Could not save this plan. Try again.');setSaveStatus('Saved to your member profile.');}catch(e){setSaveStatus(e.message);}finally{setSaving(false);}}
 function calculate(){setError('');try{const options={selections,currentLevels,inventory,modifiers,includePrerequisites,kind:construction?'construction':'research'};setResult(mode==='reach'?calculateReach(dataset,options):calculateCosts(dataset,options));}catch(e){setError(e.message);}}
 function download(){const url=URL.createObjectURL(new Blob([exportPlanCsv(result)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${toolKey}-upgrade-plan.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className={styles.planner}>
  <div className={styles.topline}><span>{dataset.items.length} {construction?'buildings':'research entries'} · {dataset.items.reduce((n,i)=>n+i.levels.length,0)} level records</span><span role="status">{loading?'Loading saved plan…':saveStatus}</span></div>
  <fieldset className={styles.inputs} disabled={loading}>
   <section className={styles.panel}>
    <div className={styles.sectionHead}><div><span className={styles.eyebrow}>01 · Upgrade plan</span><h2>What are you upgrading?</h2></div><div className={styles.mode} aria-label="Calculation mode"><button type="button" aria-pressed={mode==='cost'} onClick={()=>{changed();setMode('cost');}}>Calculate cost</button><button type="button" aria-pressed={mode==='reach'} onClick={()=>{changed();setMode('reach');}}>What can I afford?</button></div></div>
    <div className={styles.finder}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Find {construction?'a building':'research'}<input type="search" placeholder={construction?'e.g. Town Center':'Name or effect'} value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Select an upgrade<select value={chosen?.id||''} onChange={e=>setCandidate(e.target.value)}>{filtered.length?filtered.map(i=><option key={i.id} value={i.id}>{i.name} · {i.category}</option>):<option value="">No matching items</option>}</select></label><button type="button" className={styles.quiet} onClick={add} disabled={!chosen||selections.some(s=>s.id===chosen.id)}>Add upgrade</button></div>
    <div className={styles.selections}>{selections.map(s=>{const item=dataset.items.find(i=>i.id===s.id);return <div className={styles.selection} key={s.id}><div><strong>{item.name}</strong><small>{item.category}{item.levels[0]?.effect?.type?` · ${item.levels[0].effect.type}`:''}</small></div><label>Current<LevelSelect item={item} value={s.current} label={`${item.name} (${item.category}) current level`} onChange={v=>updateSelection(s.id,'current',v)}/></label><span className={styles.arrow}>→</span><label>{mode==='reach'?'Maximum target':'Target'}<LevelSelect item={item} value={s.target} minimum={s.current} label={`${item.name} (${item.category}) target level`} onChange={v=>updateSelection(s.id,'target',v)}/></label><button type="button" className={styles.remove} aria-label={`Remove ${item.name} (${item.category})`} onClick={()=>{changed();setSelections(prev=>prev.filter(x=>x.id!==s.id));}}>Remove</button></div>;})}</div>
    {!selections.length&&<p>Add an upgrade to begin.</p>}
    <label className={styles.check}><input type="checkbox" checked={includePrerequisites} onChange={e=>{changed();setIncludePrerequisites(e.target.checked);}}/>Include prerequisite {construction?'buildings':'research'}</label>
    <p className={styles.hint}>Set completed levels below so prerequisites you already own are not counted. Unset items are treated as not started.</p>
    <details className={styles.details}><summary>Completed {construction?'building':'research'} levels</summary><label>Find a completed item<input type="search" value={baselineSearch} onChange={e=>setBaselineSearch(e.target.value)} placeholder="Search by name"/></label><div className={styles.baseline}>{dataset.items.filter(i=>`${i.name} ${i.category}`.toLowerCase().includes(baselineSearch.toLowerCase())).map(i=><label key={i.id}><span>{i.name}<small>{i.category}</small></span><LevelSelect item={i} value={selections.find(s=>s.id===i.id)?.current||currentLevels[i.id]||'0'} label={`Completed ${i.name} (${i.category}) level`} onChange={v=>{changed();setCurrentLevels(c=>({...c,[i.id]:v}));if(selections.some(s=>s.id===i.id))updateSelection(i.id,'current',v);}}/></label>)}</div></details>
   </section>
   <div className={styles.settings}>
    <section className={styles.panel}><span className={styles.eyebrow}>02 · Inventory</span><h2>Resources you already have</h2><p className={styles.hint}>{mode==='reach'?'Enter inventory to find the highest affordable level. Use one upgrade target in this mode.':'Optional. These amounts are subtracted from the resources required.'}</p><div className={styles.fields}>{resources.map(k=><label key={k}>{RESOURCE_LABELS[k]}<input type="number" min="0" step="1" value={inventory[k]??''} placeholder="0" onChange={e=>{changed();setInventory(v=>({...v,[k]:e.target.value}));}}/></label>)}</div></section>
    <section className={styles.panel}><span className={styles.eyebrow}>03 · Time &amp; bonuses</span><h2>{construction?'Construction':'Research'} speed</h2><label>Total {construction?'construction':'research'} speed (%)<input type="number" min="0" value={modifiers.speed??''} placeholder="0" onChange={e=>modifier('speed',e.target.value)}/></label><p className={styles.hint}>Use the total shown in your Power bonus overview. Do not add an active bonus twice. Time is divided by 1 + speed ÷ 100; alliance helps are excluded.</p>{construction&&<><div className={styles.fields}><label>Additional Gray Wolf bonus (%)<input type="number" min="0" value={modifiers.wolf??''} placeholder="0" onChange={e=>modifier('wolf',e.target.value)}/></label><label>Saul skill level<select value={modifiers.saul||0} onChange={e=>modifier('saul',e.target.value)}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'None':`Level ${n} · ${n*3}% RSS reduction`}</option>)}</select></label></div><p className={styles.hint}>Saul reduces Bread, Wood, Stone and Iron costs. True Gold and Tempered True Gold costs stay the same.</p><strong className={styles.buffHeading}>Planning bonuses not already active</strong>{[['minister','Chief Minister (+10%)'],['highKing','High King: Chief Minister becomes +15%'],['groundworks','Groundworks (+10%)'],['kvk','KvK bonus (+5%)'],['doubleTime','Double Time (20% time reduction)']].map(([key,label])=><label className={styles.check} key={key}><input type="checkbox" checked={!!modifiers[key]} onChange={e=>modifier(key,e.target.checked)}/>{label}</label>)}</>}
    </section>
   </div>
   <div className={styles.actions}><button type="button" className={styles.primary} disabled={!selections.length} onClick={calculate}>{mode==='reach'?'Find affordable level':'Calculate upgrade plan'}</button><button type="button" className={styles.quiet} disabled={saving} onClick={save}>{saving?'Saving…':'Save inputs'}</button></div>
  </fieldset>
  {error&&<p role="alert" className={styles.warning}>{error}</p>}
  {result?<section className={styles.results} aria-label="Calculation results" aria-live="polite"><div className={styles.sectionHead}><div><span className={styles.eyebrow}>Your results</span><h2>{result.reachedLevel?`Affordable through ${levelLabel(result.reachedLevel)}`:'Upgrade requirements'}</h2></div><button type="button" className={styles.quiet} onClick={download}>Download CSV</button></div>
   <div className={styles.metrics}><div><span>Upgrade steps</span><strong>{result.steps.length}</strong><small>{result.steps.filter(s=>s.prerequisite).length} prerequisite steps</small></div><div><span>Adjusted time</span><strong>{duration(result.seconds)}</strong><small>Base time: {duration(result.baseSeconds)}</small></div><div><span>Power gained</span><strong>{fmt(result.power)}</strong><small>{construction?'Where reported by the source':'Research power increases'}</small></div></div>
   <div className={styles.tableWrap}><table><caption>Resources needed for the full plan</caption><thead><tr><th>Resource</th><th>Required</th><th>Owned</th><th>Still needed</th></tr></thead><tbody>{resources.map(k=><tr key={k}><th>{RESOURCE_LABELS[k]}</th><td>{fmt(result.totals[k])}</td><td>{fmt(numberValue(inventory[k]))}</td><td className={result.shortfall[k]?styles.shortfall:styles.covered}>{fmt(result.shortfall[k])}</td></tr>)}</tbody></table></div>
   {result.buildingRequirements.length>0&&<p className={styles.warning}>Building requirements: {result.buildingRequirements.join(', ')}. Building upgrade costs are not included in research totals.</p>}
   {result.unverified&&<p className={styles.warning}>This plan includes levels the reference dataset has not marked as verified. Check these costs in-game before spending.</p>}
   {!!result.warnings.length&&<details className={styles.warning} open><summary>Prerequisites to check ({result.warnings.length})</summary><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}
   <details className={styles.details}><summary>Level-by-level breakdown ({result.steps.length} steps)</summary><div className={styles.tableWrap}><table><thead><tr><th>Upgrade</th>{resources.map(k=><th key={k}>{RESOURCE_LABELS[k]}</th>)}<th>Time</th></tr></thead><tbody>{result.steps.map(s=><tr key={s.key}><th>{s.name}<small>{s.category} · {levelLabel(s.level)}{s.prerequisite?' · Prerequisite':''}</small></th>{resources.map(k=><td key={k}>{fmt(s.costs[k])}</td>)}<td>{duration(s.adjustedSeconds)}</td></tr>)}</tbody></table></div></details>
  </section>:<div className={styles.empty}><h2>Your upgrade plan appears here</h2><p>Choose current and target levels, then calculate to see materials and time.</p></div>}
  <footer className={styles.source}>Level costs: <a href={dataset.source} target="_blank" rel="noreferrer">Kingshot Optimizer reference data</a> · Retrieved {dataset.retrievedAt}. Your kingdom must have unlocked the selected tiers.</footer>
 </div>;
}
