'use client';
import {useMemo,useState} from 'react';
import styles from './ProgressionPlanner.module.css';
import {GOVERNOR_GEAR_LEVELS,sumGovernorGear} from '../../lib/progressionTools.mjs';
const SLOTS=['Infantry Head','Infantry Body','Cavalry Head','Cavalry Body','Archer Head','Archer Body'];
const fmt=n=>Math.round(n).toLocaleString();
export default function GovernorGearPlanner(){
 const [rows,setRows]=useState(()=>SLOTS.map((name,i)=>({name,from:0,to:i<2?4:2}))),[stock,setStock]=useState({satin:0,threads:0,visions:0});
 const total=useMemo(()=>rows.reduce((a,r)=>{const c=sumGovernorGear(r.from,r.to);return{satin:a.satin+c.satin,threads:a.threads+c.threads,visions:a.visions+c.visions}},{satin:0,threads:0,visions:0}),[rows]);
 const edit=(i,key,value)=>setRows(old=>old.map((r,n)=>n===i?{...r,[key]:Number(value),...(key==='from'&&r.to<Number(value)?{to:Number(value)}:{})}:r));
 return <section className={styles.shell}><div className={styles.toolbar}><div><span className="k-mark">Six-piece loadout</span><strong>Green through Red T6</strong></div><button onClick={()=>setRows(SLOTS.map(name=>({name,from:0,to:0})))}>Reset</button></div><div className={styles.layout}><div className={styles.inputs}><section className={styles.section}><div className={styles.head}><h2>Gear targets</h2><p>Current level is already owned.</p></div><div className={styles.gearTable}>{rows.map((row,i)=><div className={styles.gearRow} key={row.name}><strong>{row.name}</strong><select aria-label={`${row.name} current level`} value={row.from} onChange={e=>edit(i,'from',e.target.value)}>{GOVERNOR_GEAR_LEVELS.map(x=><option key={x.index} value={x.index}>{x.label}</option>)}</select><span className={styles.arrow}>→</span><select aria-label={`${row.name} target level`} value={row.to} onChange={e=>edit(i,'to',e.target.value)}>{GOVERNOR_GEAR_LEVELS.map(x=><option key={x.index} value={x.index} disabled={x.index<row.from}>{x.label}</option>)}</select></div>)}</div></section><section className={styles.section}><div className={styles.head}><h2>Inventory</h2><p>Used to calculate what is still missing.</p></div><div className={styles.fields}>{Object.keys(stock).map(key=><label className={styles.field} key={key}><span>{key==='threads'?'Gilded Threads':key==='visions'?"Artisan's Vision":'Satin'}</span><input aria-label={`${key} inventory`} type="number" min="0" value={stock[key]} onChange={e=>setStock({...stock,[key]:Math.max(0,Number(e.target.value)||0)})}/></label>)}</div></section></div><aside className={styles.results}><span className="k-mark">Live result</span><h2>Material plan</h2><div className={styles.summary}>{Object.entries(total).map(([key,value])=>{const missing=Math.max(0,value-stock[key]);return <div key={key}><span>{key==='threads'?'Gilded Threads':key==='visions'?"Artisan's Vision":'Satin'} required</span><strong>{fmt(value)}</strong><span>Still needed</span><strong className={missing?styles.short:styles.covered}>{fmt(missing)}</strong></div>})}</div><div className={styles.note}>Set bonuses depend on matching thresholds across three or six pieces. This calculator totals materials; it does not assume one troop priority fits every account.</div><p className={styles.source}>Data checked against the <a href="https://kingshot.net/database/governor-gear" target="_blank" rel="noreferrer">Kingshot.net Governor Gear database</a>.</p></aside></div></section>
}
