'use client';
import Image from 'next/image';
import {useMemo,useState} from 'react';
import styles from './ProgressionPlanner.module.css';
import {GOVERNOR_GEAR_LEVELS,sumGovernorGear} from '../../lib/progressionTools.mjs';
const SLOTS=[['Infantry Head','infantry-head.webp'],['Infantry Body','infantry-body.webp'],['Cavalry Head','cavalry-head.webp'],['Cavalry Body','cavalry-body.webp'],['Archer Head','archer-head.webp'],['Archer Body','archer-body.webp']];
const RESOURCES={satin:['Satin','satin.webp'],threads:['Gilded Threads','gilded-threads.webp'],visions:["Artisan\'s Vision",'artisans-vision.webp']};
const fmt=n=>Math.round(n).toLocaleString();
export default function GovernorGearPlanner(){
 const blank=()=>SLOTS.map(([name,image])=>({name,image,from:-1,to:0}));
 const [rows,setRows]=useState(blank),[stock,setStock]=useState({satin:0,threads:0,visions:0});
 const total=useMemo(()=>rows.reduce((a,r)=>{const c=sumGovernorGear(r.from,r.to);return{satin:a.satin+c.satin,threads:a.threads+c.threads,visions:a.visions+c.visions}},{satin:0,threads:0,visions:0}),[rows]);
 const edit=(i,key,value)=>setRows(old=>old.map((r,n)=>n===i?{...r,[key]:Number(value),...(key==='from'&&r.to<Number(value)?{to:Number(value)}:{})}:r));
 const options=(row,key)=><><option value={-1}>No gear</option>{GOVERNOR_GEAR_LEVELS.map(x=><option key={x.index} value={x.index} disabled={key==='to'&&x.index<row.from}>{x.label}</option>)}</>;
 return <section className={styles.shell}><div className={styles.toolbar}><div><span className="k-mark">Six-piece loadout</span><strong>Exact Green → Red T6 material planner</strong></div><button onClick={()=>setRows(blank())}>Reset</button></div><div className={styles.layout}><div className={styles.inputs}><section className={styles.section}><div className={styles.head}><h2>Governor Gear targets</h2><p>Current stage is already paid for; target stage is included.</p></div><div className={styles.gearTable}>{rows.map((row,i)=><div className={styles.gearRow} key={row.name}><div className={styles.piece}><Image src={`/images/tools/governor-gear/${row.image}`} width={62} height={62} alt=""/><strong>{row.name}</strong></div><select aria-label={`${row.name} current level`} value={row.from} onChange={e=>edit(i,'from',e.target.value)}>{options(row,'from')}</select><span className={styles.arrow}>→</span><select aria-label={`${row.name} target level`} value={row.to} onChange={e=>edit(i,'to',e.target.value)}>{options(row,'to')}</select></div>)}</div></section><section className={styles.section}><div className={styles.head}><h2>Your inventory</h2><p>Subtracted from the exact upgrade total.</p></div><div className={styles.fields}>{Object.entries(RESOURCES).map(([key,[label,image]])=><label className={styles.resourceField} key={key}><Image src={`/images/tools/resources/${image}`} width={38} height={38} alt=""/><span>{label}</span><input aria-label={`${key} inventory`} type="number" min="0" value={stock[key]} onChange={e=>setStock({...stock,[key]:Math.max(0,Number(e.target.value)||0)})}/></label>)}</div></section></div><aside className={styles.results}><span className="k-mark">Live result</span><h2>Material plan</h2><div className={styles.summary}>{Object.entries(total).map(([key,value])=>{const [label,image]=RESOURCES[key],missing=Math.max(0,value-stock[key]);return <div key={key} className={styles.resourceResult}><Image src={`/images/tools/resources/${image}`} width={42} height={42} alt=""/><span>{label} required</span><strong>{fmt(value)}</strong><small>Still needed</small><strong className={missing?styles.short:styles.covered}>{fmt(missing)}</strong></div>})}</div><div className={styles.note}>A “No gear” start includes the Green crafting cost. Every other start assumes the selected current stage is complete.</div><p className={styles.source}>Progression data and gear art checked against <a href="https://kingshotoptimizer.com/governor-gear/references/" target="_blank" rel="noreferrer">Kingshot Optimizer’s Governor Gear references</a>.</p></aside></div></section>;
}
