create table if not exists public.member_auth_identities (
  id bigint generated by default as identity primary key,
  provider text not null check (provider in ('discord', 'kingshot')),
  provider_user_id text not null,
  member_id text not null,
  provider_label text,
  metadata jsonb not null default '{}'::jsonb,
  last_verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_user_id),
  unique (provider, member_id)
);

create index if not exists member_auth_identities_member_idx
  on public.member_auth_identities (member_id);

alter table public.member_auth_identities enable row level security;

comment on table public.member_auth_identities is
  'Server-only mapping between verified external identities and K710 member IDs. Access via service role only.';
