import uiStrings from '../../../public/ui-strings.json';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 30;

// Generated by scripts/extract-ui-strings.js and committed so a bare
// `next build` resolves this import on a fresh clone. Guard the shape
// anyway: a malformed file should narrow the allowlist, never throw.
const ALLOWED = new Set(
  (Array.isArray(uiStrings) ? uiStrings : []).map((value) => normalize(value)),
);
const MAX_STRINGS = 64;
const MAX_STRING_LENGTH = 320;

// Public LibreTranslate mirrors are used only for static, allow-listed K710 UI copy.
// Player-entered values never reach this route. An operator can override this list
// with K710_LIBRETRANSLATE_URLS (comma-separated) or point it at a self-hosted instance.
const DEFAULT_MIRRORS = [
  'https://translate.flossboxin.org.in',
  'https://translate.terraprint.co',
  'https://translate.argosopentech.com',
  'https://lt.blitzw.in',
];

const LANGUAGE_ALIASES = new Map([
  ['english', 'en'], ['en', 'en'],
  ['albanian', 'sq'], ['sq', 'sq'],
  ['arabic', 'ar'], ['العربية', 'ar'], ['ar', 'ar'],
  ['azerbaijani', 'az'], ['az', 'az'],
  ['basque', 'eu'], ['eu', 'eu'],
  ['bengali', 'bn'], ['বাংলা', 'bn'], ['bn', 'bn'],
  ['bulgarian', 'bg'], ['bg', 'bg'],
  ['catalan', 'ca'], ['ca', 'ca'],
  ['chinese', 'zh'], ['chinese simplified', 'zh'], ['chinese (simplified)', 'zh'], ['简体中文', 'zh'], ['zh', 'zh'],
  ['chinese traditional', 'zt'], ['chinese (traditional)', 'zt'], ['繁體中文', 'zt'], ['zt', 'zt'],
  ['czech', 'cs'], ['čeština', 'cs'], ['cs', 'cs'],
  ['danish', 'da'], ['dansk', 'da'], ['da', 'da'],
  ['dutch', 'nl'], ['nederlands', 'nl'], ['nl', 'nl'],
  ['esperanto', 'eo'], ['eo', 'eo'],
  ['estonian', 'et'], ['et', 'et'],
  ['finnish', 'fi'], ['suomi', 'fi'], ['fi', 'fi'],
  ['french', 'fr'], ['français', 'fr'], ['francais', 'fr'], ['fr', 'fr'],
  ['galician', 'gl'], ['gl', 'gl'],
  ['german', 'de'], ['deutsch', 'de'], ['de', 'de'],
  ['greek', 'el'], ['ελληνικά', 'el'], ['el', 'el'],
  ['hebrew', 'he'], ['עברית', 'he'], ['he', 'he'],
  ['hindi', 'hi'], ['हिन्दी', 'hi'], ['हिंदी', 'hi'], ['hi', 'hi'],
  ['hungarian', 'hu'], ['magyar', 'hu'], ['hu', 'hu'],
  ['indonesian', 'id'], ['bahasa indonesia', 'id'], ['id', 'id'],
  ['irish', 'ga'], ['ga', 'ga'],
  ['italian', 'it'], ['italiano', 'it'], ['it', 'it'],
  ['japanese', 'ja'], ['日本語', 'ja'], ['ja', 'ja'],
  ['korean', 'ko'], ['한국어', 'ko'], ['ko', 'ko'],
  ['kyrgyz', 'ky'], ['ky', 'ky'],
  ['latvian', 'lv'], ['lv', 'lv'],
  ['lithuanian', 'lt'], ['lt', 'lt'],
  ['malay', 'ms'], ['bahasa melayu', 'ms'], ['ms', 'ms'],
  ['norwegian', 'nb'], ['norsk', 'nb'], ['nb', 'nb'], ['no', 'nb'],
  ['persian', 'fa'], ['farsi', 'fa'], ['فارسی', 'fa'], ['fa', 'fa'],
  ['polish', 'pl'], ['polski', 'pl'], ['pl', 'pl'],
  ['portuguese', 'pt'], ['português', 'pt'], ['portugues', 'pt'], ['pt', 'pt'],
  ['portuguese brazil', 'pb'], ['portuguese (brazil)', 'pb'], ['brazilian portuguese', 'pb'], ['pb', 'pb'],
  ['romanian', 'ro'], ['română', 'ro'], ['romana', 'ro'], ['ro', 'ro'],
  ['russian', 'ru'], ['русский', 'ru'], ['ru', 'ru'],
  ['slovak', 'sk'], ['sk', 'sk'],
  ['slovenian', 'sl'], ['sl', 'sl'],
  ['spanish', 'es'], ['español', 'es'], ['espanol', 'es'], ['es', 'es'],
  ['swedish', 'sv'], ['svenska', 'sv'], ['sv', 'sv'],
  ['tagalog', 'tl'], ['filipino', 'tl'], ['tl', 'tl'],
  ['thai', 'th'], ['ไทย', 'th'], ['th', 'th'],
  ['turkish', 'tr'], ['türkçe', 'tr'], ['turkce', 'tr'], ['tr', 'tr'],
  ['ukrainian', 'uk'], ['ukranian', 'uk'], ['українська', 'uk'], ['uk', 'uk'],
  ['urdu', 'ur'], ['اردو', 'ur'], ['ur', 'ur'],
  ['vietnamese', 'vi'], ['tiếng việt', 'vi'], ['tieng viet', 'vi'], ['vi', 'vi'],
]);

const cache = globalThis.__k710UiTranslationCache || new Map();
globalThis.__k710UiTranslationCache = cache;

function normalize(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function normalizeLanguage(value) {
  return normalize(value)
    .toLocaleLowerCase('en-US')
    .replace(/[._-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function sameOrigin(request) {
  const origin = request.headers.get('origin');
  const host = request.headers.get('host');
  if (!origin || !host) return false;
  try {
    return new URL(origin).host === host;
  } catch {
    return false;
  }
}

function resolveLanguageCode(language) {
  const normalized = normalizeLanguage(language);
  return LANGUAGE_ALIASES.get(normalized) || null;
}

function getMirrors() {
  const configured = normalize(process.env.K710_LIBRETRANSLATE_URLS || '');
  const mirrors = configured
    ? configured.split(',').map((value) => value.trim()).filter(Boolean)
    : DEFAULT_MIRRORS;
  return [...new Set(mirrors.map((value) => value.replace(/\/+$/, '')))];
}

async function translateAtMirror(baseUrl, strings, target) {
  const response = await fetch(`${baseUrl}/translate`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'K710Hub/1.0 static-ui-translation',
    },
    body: JSON.stringify({
      q: strings,
      source: 'en',
      target,
      format: 'text',
    }),
    cache: 'no-store',
    signal: AbortSignal.timeout(8_000),
  });

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(`${baseUrl} returned ${response.status}: ${detail.slice(0, 160)}`);
  }

  const payload = await response.json();
  const translated = payload?.translatedText;
  if (!Array.isArray(translated) || translated.length !== strings.length) {
    throw new Error(`${baseUrl} returned an invalid translation payload`);
  }
  if (translated.some((value) => typeof value !== 'string')) {
    throw new Error(`${baseUrl} returned a non-string translation`);
  }

  return { translated, provider: baseUrl };
}

async function translateWithMyMemory(strings, target) {
  const translated = new Array(strings.length);
  const CONCURRENCY = 6;

  for (let start = 0; start < strings.length; start += CONCURRENCY) {
    const batch = strings.slice(start, start + CONCURRENCY);
    const values = await Promise.all(batch.map(async (source) => {
      const params = new URLSearchParams({
        q: source,
        langpair: `en|${target}`,
        mt: '1',
      });

      const response = await fetch(`https://api.mymemory.translated.net/get?${params.toString()}`, {
        headers: { 'User-Agent': 'K710Hub/1.0 static-ui-translation' },
        cache: 'no-store',
        signal: AbortSignal.timeout(8_000),
      });

      if (!response.ok) {
        const detail = await response.text().catch(() => '');
        throw new Error(`MyMemory returned ${response.status}: ${detail.slice(0, 160)}`);
      }

      const payload = await response.json();
      const value = payload?.responseData?.translatedText;
      if (typeof value !== 'string' || !value.trim()) {
        throw new Error('MyMemory returned an invalid translation payload');
      }
      return value;
    }));

    values.forEach((value, offset) => {
      translated[start + offset] = value;
    });
  }

  return { translated, provider: 'mymemory' };
}

async function translateWithFallback(strings, target) {
  const mirrors = getMirrors();
  const attempts = mirrors.map((baseUrl) =>
    translateAtMirror(baseUrl, strings, target).catch((error) => {
      console.warn('K710 LibreTranslate mirror failed', error?.message || error);
      throw error;
    }),
  );

  try {
    return await Promise.any(attempts);
  } catch (error) {
    console.error('K710 all LibreTranslate mirrors failed', error?.message || error);
  }

  if (target === 'tl') {
    try {
      return await translateWithMyMemory(strings, target);
    } catch (error) {
      console.error('K710 Tagalog MyMemory fallback failed', error?.message || error);
    }
  }

  return null;
}

export async function POST(request) {
  if (!sameOrigin(request)) {
    return Response.json({ error: 'Same-origin requests only.' }, { status: 403 });
  }

  let body;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  const language = normalize(body?.language);
  const strings = Array.isArray(body?.strings) ? body.strings.map(normalize) : [];

  if (!language || language.length > 80 || /[\u0000-\u001f]/.test(language)) {
    return Response.json({ error: 'Invalid target language.' }, { status: 400 });
  }

  if (!strings.length || strings.length > MAX_STRINGS) {
    return Response.json({ error: `Send between 1 and ${MAX_STRINGS} strings.` }, { status: 400 });
  }

  if (strings.some((value) => !value || value.length > MAX_STRING_LENGTH || !ALLOWED.has(value))) {
    return Response.json({ error: 'Only static K710 interface strings may be translated.' }, { status: 400 });
  }

  const target = resolveLanguageCode(language);
  if (!target) {
    return Response.json(
      {
        error: `“${language}” is not currently supported by the free translation engine.`,
        code: 'UNSUPPORTED_LANGUAGE',
      },
      { status: 422 },
    );
  }

  if (target === 'en') {
    return Response.json({ translated: strings, provider: 'original' });
  }

  const results = new Array(strings.length);
  const misses = [];
  const missIndexes = [];

  strings.forEach((source, index) => {
    const key = `${target}\u0000${source}`;
    const cached = cache.get(key);
    if (cached) {
      results[index] = cached;
    } else {
      misses.push(source);
      missIndexes.push(index);
    }
  });

  let provider = 'memory-cache';
  if (misses.length) {
    const translated = await translateWithFallback(misses, target);
    if (!translated) {
      return Response.json(
        {
          error: 'Translation providers are temporarily unavailable.',
          code: 'PROVIDER_UNAVAILABLE',
          retryAfter: 60,
        },
        {
          status: 503,
          headers: { 'Retry-After': '60' },
        },
      );
    }

    provider = translated.provider;
    translated.translated.forEach((value, offset) => {
      const index = missIndexes[offset];
      const source = strings[index];
      results[index] = value;
      cache.set(`${target}\u0000${source}`, value);
    });

    // Prevent unbounded growth in long-lived function instances.
    if (cache.size > 12000) {
      const removeCount = cache.size - 9000;
      const iterator = cache.keys();
      for (let i = 0; i < removeCount; i += 1) {
        const next = iterator.next();
        if (next.done) break;
        cache.delete(next.value);
      }
    }
  }

  return Response.json(
    { translated: results, provider },
    {
      headers: {
        'Cache-Control': 'private, max-age=0, must-revalidate',
      },
    },
  );
}
