export const dynamic = 'force-dynamic';
import Link from 'next/link';
import GovernorGearOptimizer from '../GovernorGearOptimizer';

export const metadata = { title: 'Governor Gear Optimizer · K710' };

export default async function GovernorGearOptimizerPage({ searchParams: searchParamsPromise }) {
  const searchParams = await searchParamsPromise;
  const memberId = typeof searchParams?.member_id === 'string' ? searchParams.member_id : '';
  const query = memberId ? `?member_id=${encodeURIComponent(memberId)}` : '';
  return <main className="armory governor-gear-page"><div className="armory-atmos" aria-hidden="true"/><span className="armory-rack-l" aria-hidden="true"/><span className="armory-rack-r" aria-hidden="true"/><div className="armory-inner governor-gear-inner"><div className="governor-gear-nav"><Link href={`/tools?category=Governor Gear${memberId ? `&member_id=${encodeURIComponent(memberId)}` : ''}`}>← Governor Gear tools</Link><span className="k-mark">Governor Gear</span></div><header className="armory-head governor-gear-head"><h1 className="k-display armory-title">Governor Gear Optimizer</h1><p className="k-narrative armory-lede">Set current and target tiers for all 6 Governor Gear pieces, track Defense/Attack set bonuses, and see the total Satin, Gilded Threads, and Artisan&apos;s Vision required.</p></header><GovernorGearOptimizer/></div><footer className="governor-gear-source">Tier costs: <a href="https://www.reddit.com/r/KingShot/comments/1ons4ib/governor_gear_matrix/" target="_blank" rel="noreferrer">community Governor Gear Matrix (r/KingShot)</a> and the <a href="https://kingshot.fandom.com/wiki/Governor_Gear" target="_blank" rel="noreferrer">Kingshot Fandom Wiki</a> (CC-BY-SA). Red T5/T6 costs are not yet sourced — see the Preview notice in the results panel.</footer><style>{`.governor-gear-page{color:var(--parchment)}.governor-gear-inner{width:min(1380px,100%);padding-top:clamp(76px,9vh,108px)}.governor-gear-nav{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:24px;padding-bottom:15px;border-bottom:1px solid var(--edge)}.governor-gear-nav a{color:var(--brass);font-family:var(--font-body);font-size:12px;letter-spacing:.05em;text-decoration:none}.governor-gear-nav a:hover{color:var(--gold-hot)}.governor-gear-head{margin-bottom:24px}.governor-gear-head .armory-lede{max-width:760px}.governor-gear-source{width:min(1380px,100%);margin:20px auto 0;padding:14px 4px;color:var(--t-secondary);font-size:11px;line-height:1.6}.governor-gear-source a{color:var(--brass)}@media(max-width:620px){.governor-gear-nav{align-items:flex-start;flex-direction:column}.governor-gear-inner{padding-top:70px}}`}</style></main>;
}
